version: '3.8'
services:
  samba:
    container_name: samba
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SMB_USER: user
        SMB_PASSWORD: pass
    volumes:
      - /mnt:/mnt:ro
    tty: yes
    restart: always
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    networks:
      - default

networks:
  default: